name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/resuable_lint.yml    
    with:
      python-version: '3.11'

  test:
    uses: ./.github/workflows/resuable_test.yml    
    with:
      python-version: '3.11'
    secrets:
      secret: ${{ secrets.secret }}      

  summary:
    runs-on: ubuntu-latest
    needs: [lint, test]                             
    steps:
      - name: All checks passed
        run: echo "Lint and Tests passed successfully!"
